spring:
  application:
    name: MessageBoard
  session:
    cookie:
      same-site: none
      secure: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/messageboard?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 87651361
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.andy.messageboard.entity
  configuration:
    map-underscore-to-camel-case: true